# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dvec_C <- function(L) {
    .Call('_SC_dvec_C', PACKAGE = 'SC', L)
}

offsubsum <- function(A, x, i, S) {
    .Call('_SC_offsubsum', PACKAGE = 'SC', A, x, i, S)
}

rcpparma_hello_world <- function() {
    .Call('_SC_rcpparma_hello_world', PACKAGE = 'SC')
}

rcpparma_outerproduct <- function(x) {
    .Call('_SC_rcpparma_outerproduct', PACKAGE = 'SC', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_SC_rcpparma_innerproduct', PACKAGE = 'SC', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_SC_rcpparma_bothproducts', PACKAGE = 'SC', x)
}

